version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: wandr1
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: wandr
    networks:
      - backend
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wandr
      MYSQL_DATABASE: wandr1
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
