version: "3.7"

services:
  server:
    image: mcslender/wandr-k8-deploy
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - "3000:3000"

    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - backend
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
